### ISSUE TITLE
Difference between ongdb and ongdb-enterprise.

### ISSUE THREAD

**Issue by shamil** [graphfoundation/docker-ongdb-publish#1]
I see that there is 2 type of images in `dockerhub`

* https://hub.docker.com/r/graphfoundation/ongdb
* https://hub.docker.com/r/graphfoundation/ongdb-enterprise

It seems they have same hash on both of them, is there any differences?

**Comment by bradnussbaum** [comment]
We are currently in the process of migrating these repositories for the ONgDB development changes occurring. Our build server that publishes docker images has not been fully transitioned but will be shortly. Going forward, we will be producing an ONgDB Community Edition licensed under GPLV3 and an ONgDB Enterprise Edition licensed under AGPLv3. 

There will be new directories to represent the two editions in this git repository and they will be published to Docker Hub as follows:

ONgDB Community Edition - https://hub.docker.com/r/graphfoundation/ongdb
ONgDB Enterprise Edition - https://hub.docker.com/r/graphfoundation/ongdb-enterprise


For more details on the changes happening please see the following official statement: https://www.graphfoundation.org/graph-foundation-resolution-for-future-ongdb-development/

**Comment by fazlulkarimweb** [comment]
@bradnussbaum At first, I want to thank you and your team for this wonderful initiative. I have a few questions?
1. You have said that you will release the changes soon and publish ONgDB 1.0 alpha. Can you please tell us approximately how many weeks or months it will take? 
2.  Will ONgDB Enterprise and community edition have the multi-database feature from the beginning?  
3. In terms of features, what major differences we will be seeing in the community and enterprise edition in the coming days?

Thank you again for this initiative.

**Comment by bradnussbaum** [comment]
@fazlulkarimweb ONgDB 1.0 alpha is out. Please have a loot at it and send any feedback. ONgDB 1.0 will not have multi-database support. We are planning multi-database support for 2.0 which has already been under development now for a couple years. The difference between Community and Enterprise is more related to scalability and performance features. Enterprise edition has causal clustering, backups, restore, slotted runtime, metrics and enhanced security.

**Comment by fazlulkarimweb** [comment]
@bradnussbaum Thanks for the generous reply. I'm thinking about using ONgDB Enterprise in production. But I've seen that it is currently licensed under an AGPL license. Can I use it for free without any major future commercial, legal, or vendor lock-in restrictions? I'm just trying to be reassured because of the past unfair legal practices of Neo4j. Again thanks for this open-source project.

**Comment by bradnussbaum** [comment]
@fazlulkarimweb AGPLv3 is an open source license under the copyright of the Free Software Foundation. You can read more about the AGPLv3 license to see if it suitable for your usage on the FSF site at: https://www.gnu.org/licenses/why-affero-gpl.html
