### ISSUE TITLE
Publish an image using JRE 11 

### ISSUE THREAD

**Issue by iRevive** [graphfoundation/docker-ongdb-publish#2]
Java 8 does not respect memory and CPU limits provided by docker. 
Currently, both `memory` and `-Xmx` options need to be specified to apply the memory limit correctly:
```shell
docker run ... --memory=8Gi -e JAVA_OPTS=-Xmx7900m graphfoundation/ongdb:1.0
```

This issue was resolved in Java 9 release https://developers.redhat.com/blog/2017/03/14/java-inside-docker.

First LTS release after Java 9 is Java 11.

**Comment by bradnussbaum** [comment]
@iRevive Is there a way we could handle this better right now with Java 8? When 2.0 comes out it will be Java 11. I don't thinking upgrading past Java 8 is in the cards for 1.0 right now.

**Comment by iRevive** [comment]
@bradnussbaum 
since it's a matter of the runtime only, the Dockerfile can be tweaked:

```dockerfile
ARG RUNTIME_IMAGE
FROM $RUNTIME_IMAGE

ENV ONGDB_SHA256=ac90ab1f8079c42bd14056eabf1f268fe9b27e190e3982ece4bee0780eb3c5be \
...
```

And build two images:
```shell
# java 8 - default image
docker build -t 1.0.0-alpha01 --build-arg RUNTIME_IMAGE=openjdk:8-jre-slim .
# java 11 image
docker build -t 1.0.0-alpha01-java11 --build-arg RUNTIME_IMAGE=adoptopenjdk/openjdk11:slim .
```

In the case of JVM 11, the service complains about inappropriate Java runtime during the startup:
```
WARNING! You are using an unsupported Java runtime.
* Please use Oracle(R) Java(TM) 8, OpenJDK(TM) or IBM J9 to run Neo4j.
...
2021-03-03 13:24:59.757+0000 WARN  You are using an unsupported Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 8, OpenJDK(TM) 8 or IBM J9.
```

But I didn't observe any runtime issue so far.

**Comment by bradnussbaum** [comment]
I don't think it would be good to run ONgDB 1.0 with the Java 11 runtime at this time. It may work for most usage but it doesn't compile right now. We are planning the upgrade to Java 11 for ONgDB 2.0 and it may be best to handle this then.
