### ISSUE TITLE
Older OngDB images on Docker Hub

### ISSUE THREAD

**Issue by msmolyak** [graphfoundation/docker-ongdb-publish#3]
Hello,

I am trying to find OngDB images of 3.5 version on Docker Hub, but they are gone. The only remaining ones are for the 1.0 version. It is not clear what the difference is between 3.5/3.6 and 1.0. One distinction I found is ongdb-shell command replacing cypher-shell. That by itself is not a problem except that I cannot connect to the database using ongdb-shell. The default invocation (without parameters) produces a "Connection refused' message.

In any case, I would like to have access to older versions of OngDB our code relies on. Are there plans to bring them back to Docker Hub, or do I have to build them locally?

Thank you,

Michael

**Comment by bradnussbaum** [comment]
Hi @msmolyak,

Graph Foundation is not longer able to support or provide distributions or source code for ONgDB 3.4, 3.5 and 3.6 releases. See the resolution for more details:
https://www.graphfoundation.org/graph-foundation-resolution-for-future-ongdb-development/

ONgDB 1.0 will be compatible with prior ONgDB 3.4 databases. For 3.5 and 3.6 a manual migration will be required which we intend to release to the community shortly.

Thank you for the ongdb-shell issue report. If you could submit a full issue report to https://github.com/graphfoundation/ongdb that would be very helpful.

**Comment by msmolyak** [comment]
Thank you for the prompt reply. How can we use APOC plugin with ONgDB 1.0?

**Comment by bradnussbaum** [comment]
@msmolyak The apoc 3.4 plugin should work with ONgDB 1.0. I am currently working on a 1.0 branch for apoc which should be available after the beta release.

**Comment by jmsuhy** [comment]
If you need to access legacy 3.5 or 3.6 versioned ongdb distros,   you can get them from https://graphstack.io :  GraphStack.io and myself are not affiliated or endorsed by the Graph Foundation  - we compile and package these as a resource for the graph community as a whole.  I just saw this issue as I am subscribed as a watcher to these projects.  You can also quite easily compile the packages as well if you prefer to do that yourself.
