### ISSUE TITLE
Missing CDN files

### ISSUE THREAD

**Issue by victorcesaroni** [graphfoundation/docker-ongdb-publish#4]
There are some missing files for Dockerfile in CDN. 

Example: [ongdb-enterprise-3.6.2-unix.tar.gz](https://cdn.graphfoundation.org/ongdb/dist/ongdb-enterprise-3.6.2-unix.tar.gz)

**Comment by bradnussbaum** [comment]
@victorcesaroni We not able to support ONgDB 3.4, 3.5 and 3.6. See https://www.graphfoundation.org/blog/graph-foundation-resolution-for-future-ongdb-development/. ONgDB 1.0 is nearly out of beta as we've had really good field testing and will be moving that toward full release. It is based on ONgDB 3.4 and there is active discussion about a 1.1 that would provide full compatibility for ONgDB 3.5 and 3.6 users. Will close this issue for now.
